// frontend/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterOutlet } from '@angular/router';
import * as signalR from "@microsoft/signalr";
import { StreamFormatter } from './stuff/StreamFormatter';


@Component({
  selector: 'app-root',
  imports: [RouterOutlet, FormsModule ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  public messageContent: string = "";
  public promptMessage: string ="";
  public enabledBtn: boolean = true;


  // For formating
  private dildo: string[] = new Array<string>();

  private connection = new signalR.HubConnectionBuilder()
    .withUrl("http://localhost:5049/prompthub")
    .build();

  private formatter = new StreamFormatter();

  async ngOnInit()
  {
    this.connection.on("ReceiveChunk", (chunk) => {
      this.formatter.appendChunk(chunk);
      
      this.messageContent = this.formatter.flush();
    });

    this.connection.on("Complete", async () => {
      console.log(this.connection.state);
      await this.connection.stop();
    });
  }

  public async doSubmit()
  {
    this.messageContent = "";
    this.formatter.clear();

    this.enabledBtn = false;

    var self = this;

    setTimeout(() => {
      self.enabledBtn = true;
    }, 15000);

    await this.connection.start();
    await this.connection.invoke("StreamChat", this.promptMessage);
  }
}

<!-- Hi there -->
<div class="container">
  <h1>Career Analyst AI</h1>
  <p>asdasdasdasdasd</p>

  <div class="promptSection">
    <input type="text" id="iPrompt" placeholder="What career are you interestted in going into?" [(ngModel)]="promptMessage"/>
  </div>
  
  <div class="actionSection">
    <button (click)="doSubmit()" [disabled]="!enabledBtn">Do stuff</button>
  </div>

  <div id="messageContent" [innerHTML]="messageContent" >
    
  </div>
</div>

// frontend_react/app/page.tsx
'use client';

import React, { useEffect, useState } from 'react';
import * as signalR from '@microsoft/signalr';
import Markdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';
import remarkGfm from 'remark-gfm'

export default function Home() {
  const [connection, setConnection] = useState<signalR.HubConnection | null>(null);
  const [promptMessage, setPromptText] = useState<string>('');
  const [promptData, setMessages] = useState<string>('');

  const handleClick = async () => {
    if (connection && connection.state === 'Connected') {
      setMessages('');

      await connection.invoke('StreamChat', promptMessage);
    }
  };


  useEffect(() => {
    const newConnection = new signalR.HubConnectionBuilder()
      .withUrl('http://localhost:5049/prompthub')
      .build();

    setConnection(newConnection);
  }, []);

  useEffect(() => {
    if (connection) {
      connection.start()
        .then(() => {
          //console.log('Connected..');

          connection.on('ReceiveChunk', (message) => {
            //console.log(message);
            setMessages(prev => prev + message);
          });
        })
        .catch((err: any) => console.error('Connection failed: ', err));
    }
  }, [connection]);

  return (
    <div className="container">
      <h1>Career Analyst AI</h1>
      <p>This is a simple example of leveraging Angular or React, C#, SignarR, and OpenAI to build a tailored AI chatbot. In this example, this chatbot is tailored to be a career analyst and give detailed, no-BS information when prompted about a career.</p>

      <div className="promptSection">
        <input type="text" id="iPrompt" placeholder="What career are you interestted in going into?" value={promptMessage} onChange={e => setPromptText(e.target.value)}/>
      </div>
      
      <div className="actionSection">
        <button onClick={handleClick}>Do stuff</button>
      </div>

      <div id="messageContent" >
        <Markdown rehypePlugins={[rehypeRaw, remarkGfm]}>{promptData}</Markdown>
      </div>
    </div>
  );
}
